- name: my copy sever
  hosts: all
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest

    - name: install apache2
      service:
        name: apache2
        state: latest 
        enabled: true

    - name: deployment
      copy:
        src: ./index.html
        dest: /var/www/html/index.html       