- name: loop installation
  hosts: all
  tasks:
    - name: print list
      debug:
        msg: "{{item}}"
      loop:
        - apple
        - banana
        - cherry  

    - name: loop check 2
      package:
        name: "{{item}}"
        state: latest
      loop:
        - vim
        - echo
        - weget    