- name: loop installation
  hosts: all
  tasks:
    - name: print list
      debug:
        msg: "{{item}}"
      loop:
        - apple
        - banana
        - cherry  

    
- name: Install packages using loop
  hosts: all
  become: yes
  tasks:
    - name: loop check 2
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - wget
        - curl
   